config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  resources :blogs
  resources :famillies, only: [:new, :create, :edit, :destroy, :update ]
  resources :rooms do
    resources :reservations, only: [:new, :create, :edit, :destroy, :update, :index ]
    resources :perks, only: [:new, :create, :edit, :destroy, :update, :index ]
  end
  resources :tasks, only: [:show, :update]
  resources :buyings, only: [:show, :update]
  resources :projects do
    resources :tasks, only: [:new, :create, :edit, :destroy, :update]
    resources :buyings, only: [:new, :create, :edit, :destroy, :update ]
    resources :usersprojects, only: [:new, :create, :edit, :destroy, :update ]
    resources :comments, only: [:new, :create, :edit, :destroy, :update ]
  end
  namespace :my do
    resources :famillies, only: [ :index ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :house
  belongs_to :user
  has_many_attached :photos
  has_rich_text :rich_body
  validates :title, presence: true
  validates :photos, presence: true
  validates :rich_body, presence: true
end

app/models/buying.rb
class Buying < ApplicationRecord
  belongs_to :project
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :project
  has_rich_text :rich_body
  validates :rich_body, presence: true
end

app/models/familly.rb
class Familly < ApplicationRecord
  has_many_attached :photos
  belongs_to :user
end

app/models/house.rb
class House < ApplicationRecord
end

app/models/perk.rb
class Perk < ApplicationRecord
end

app/models/perksroom.rb
class Perksroom < ApplicationRecord
  belongs_to :room
  belongs_to :perk
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :house
  has_one_attached :photo, dependent: :destroy
  has_rich_text :rich_body
  has_many :tasks, dependent: :destroy
  has_many :buyings, dependent: :destroy
  has_many :usersprojects, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :name, presence: true
  validates :photo, presence: true

  def value_project
    buying_value = Buying.where(project_id: self)
      sum = 0
      buying_value.each do |buying|
        sum += (buying.number * buying.value)
      end
    sum
  end

  def project_task_count
    Task.where(project_id: self).count
  end

  def project_task
    Task.where(project_id: self)
  end

  def project_task_completed
    project_task.where(completed: true).count
  end

  def project_advancement
    project_task_completed.fdiv(project_task_count) * 100
  end

  def day_until_end
    (Date.today - self.deadline).round
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_many :perks
  validates :date_in, :date_out, presence: true

  validate :no_reservation_overlap

   scope :overlapping, ->(period_start, period_end) do
      where "((date_in <= ?) and (date_out >= ?))", period_end, period_start
   end

private

  def room_reservation
    Reservation.where(room_id: self.room_id)
  end

  def no_reservation_overlap
    if (room_reservation.overlapping(date_in, date_out).any?)
       errors.add(:date_out, 'Les dates chevauchent une reservations existantes !!')
    end
  end

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :house
  has_many :reservations
  validates :name, presence: true

  def unavailable_dates
    reservations.pluck(:date_in, :date_out).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/models/roomsperk.rb
class Roomsperk < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
  has_many :usersfamillies
  has_many :blogs
  has_many :comments
  has_many :reservations
  has_many :usersprojects, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :famillies, dependent: :destroy
  validates :photo, presence: true
  # a reactiver si besoin : mail devise à personaliser
  after_create :send_welcome_email


  private

  def send_welcome_email
    UserMailer.with(user: self).welcome.deliver_now
  end

end

app/models/usersfamilly.rb
class Usersfamilly < ApplicationRecord
  belongs_to :user
  belongs_to :familly
end

app/models/usersproject.rb
class Usersproject < ApplicationRecord
  belongs_to :user
  belongs_to :project
  validates :date_start, :date_end, presence: true
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :update, :show, :destroy]
  def index
    @blogs = policy_scope(Blog.all.includes([:rich_text_rich_body]).includes([:user]))
  end

  def show
    authorize @blog
  end

  def new
    @blog = Blog.new
    authorize @blog
  end

  def edit
    @blog = Blog.find(params[:id])
    authorize @blog
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blog_path(@blog)
    else
      render :edit
    end
    authorize @blog
  end

  def create
    authorize @blog
    @blog = Blog.new(blog_params)
    @blog.house = House.find(1)
    @blog.user = current_user
    if @blog.save
      redirect_to blog_path(@blog)
    else
      render :new
    end
  end

  def destroy
    authorize @blog
    @blog.destroy
    redirect_to blogs_path
  end

  private
  def set_blog
    @blog = Blog.find(params[:id])
  end
  def blog_params
    params.require(:blog).permit(:title, :rich_body, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/perks_controller.rb
class PerksController < ApplicationController
  before_action :set_perk, only: [:edit, :update, :destroy]

  def new
    @room = Room.find(params[:room_id])
    @perk = Perk.new
    authorize @perk
  end

  def edit
    @room = Room.find(params[:room_id])
    @perk = Perk.find(params[:id])
    authorize @perk
  end

  def update
    @room = Room.find(params[:room_id])
    @perk = Perk.find(params[:id])
    authorize @perk
    if @perk.update(perk_params)
      redirect_to room_path(@room)
    else
      render :edit
    end
  end

  def create
    @room = Room.find(params[:room_id])
    @perk = Perk.new(perk_params)
    @perk.room_id = @room.id
    authorize @perk
    if @perk.save!
      redirect_to room_path(@room)
    else
      render :new
    end
  end

  def destroy
    @room = Room.find(params[:room_id])
    @perk.destroy
    authorize @perk
    redirect_to room_path(@room)
  end

  private

  def set_perk
    @perk = Perk.find(params[:id])
  end

  def perk_params
    params.require(:perk).permit(:name, :number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
      <%= cl_image_tag "https://res.cloudinary.com/dqehqrmss/image/upload/v1615998402/logo_roamid.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto text-white">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", "/", class: "nav-link text-white" %>
        </li>
         <li class="nav-item">
          <%= link_to "Rooms", rooms_path, class: "nav-link  text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Blogs", blogs_path, class: "nav-link  text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Projets", projects_path, class: "nav-link  text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Ajouter un projet", new_project_path, class: "nav-link  text-white" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo.key, width: 150, crop: :thumb, gravity: :face, class: "avatar-large dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Nouveau blog", new_blog_path, class: "dropdown-item" %>
            <%= link_to "Nouveau projet", new_project_path, class: "dropdown-item" %>
            <%= link_to "Nouvelle room", new_room_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Ma famille", my_famillies_path, class: "dropdown-item" %>
            <%= link_to "Ajout à la famille", new_familly_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Editer utilisateur", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Se deconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Se connecter", new_user_session_path, class: "nav-link  text-white" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>