config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  resources :blogs
  resources :famillies, only: [:new, :create, :edit, :destroy, :update ]
  resources :rooms do
    resources :reservations, only: [:new, :create, :edit, :destroy, :update, :index ]
    resources :perks, only: [:new, :create, :edit, :destroy, :update, :index ]
  end
  resources :tasks, only: [:show, :update]
  resources :buyings, only: [:show, :update]
  resources :projects do
    resources :tasks, only: [:new, :create, :edit, :destroy, :update]
    resources :buyings, only: [:new, :create, :edit, :destroy, :update ]
    resources :usersprojects, only: [:new, :create, :edit, :destroy, :update ]
    resources :comments, only: [:new, :create, :edit, :destroy, :update ]
  end
  namespace :my do
    resources :famillies, only: [ :index ]
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :house
  has_one_attached :photo, dependent: :destroy
  has_rich_text :rich_body
  has_many :tasks, dependent: :destroy
  has_many :buyings, dependent: :destroy
  has_many :usersprojects, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :name, presence: true
  validates :photo, presence: true

  def value_project
    buying_value = Buying.where(project_id: self)
      sum = 0
      buying_value.each do |buying|
        sum += (buying.number * buying.value)
      end
    sum
  end

  def project_task_count
    Task.where(project_id: self).count
  end

  def project_task
    Task.where(project_id: self)
  end

  def project_task_completed
    project_task.where(completed: true).count
  end

  def project_advancement
    project_task_completed.fdiv(project_task_count) * 100
  end

  def day_until_end
    (Date.today - self.deadline).round
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :show, :destroy]
  def index
    @projects = policy_scope(Project.all).reverse
  end

  def show
    @tasks = Task.where(project_id: @project)
    @buyings = Buying.where(project_id: @project)
    @task = Task.new
    @buying = Buying.new
    @usersproject = Usersproject.new
    @usersprojects = Usersproject.where(project_id: @project).includes([:user])
    @usersprojects_past = @usersprojects.where("date_end < ?", Date.today).last(5)
    @usersprojects_futur = @usersprojects.where("date_end >= ?", Date.today)
    @comment = Comment.new
    @comments = Comment.where(project_id: @project).includes([:rich_text_rich_body]).includes([:user]).last(50)
    authorize @project
  end

  def new
    @project = Project.new
    authorize @project
  end

  def edit
    @project = Project.find(params[:id])
    authorize @project
  end

  def update
    @project = Project.find(params[:id])
    authorize @project
    if @project.update(project_params)
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def create
    @project = Project.new(project_params)
    authorize @project
    @project.house = House.find(1)
    if @project.save
      task = Task.new(project_id: @project.id, name: "example")
      task.save!
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def destroy
    authorize @project
    @project.destroy
    redirect_to projects_path
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :deadline, :rich_body, :budget, :photo)
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project)  do |f| %>
  <div class="form-inputs">
    <%= f.input :name, input_html: { placeholder: "Nom du projet" } %>
    <span>Deadline</span>
    <%= f.text_field :deadline, data: { behavior: "flatpickr"}  %>
    <%= f.input :budget, input_html: { placeholder: "One million dollars !! " } %>
    <%= f.input :photo %>
  </div>
  <div class="form-inputs bg-white p-1 rounded">
    <span>Descriptif du projet :</span>
    <%= f.rich_text_area :rich_body, placeholder: 'Tu peux commencer à écrire ici...         Il est possible d\'insérer des images.' %>
  </div>
  <div class="mt-2 mb-2 pb-1 form-actions text-white container text-center">
    <%= f.button :submit, "Créer/Modifier un projet", class: "btn btn-gradient" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="container background">
    <h3>Modifies ton projet :</h3>
    <%= render "form", projects: @project %>
</div>

app/views/projects/index.html.erb
<div class="container">
  <% @projects.each do |project| %>
    <%= link_to project_path(project) do %>
    <div class="mt-1 card-project">
      <div class="bg-img"
           style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('<%= cl_image_path project.photo.key, width: 800, height: 300, :crop=>"fill" %>')">
          <div class="project-title p-4 text-white">
              <h2 class="mb-2 font-weight-bold"><%= project.name.upcase %></h2>
          </div>
      </div>
      <% end %>
      <div class="p-4">
            <p class="text-project"><%= strip_tags(project.rich_body.to_s).truncate(400)  %></p>
          <div class="mt-4 d-flex align-items-end justify-content-between">
            <%= link_to project_path(project) do %>
                <p class="no-underline mr-4 text-blue-500 hover:text-blue-400"><strong>En savoir plus</strong></p>
              <% end %>
              <p class="mr-4 text-blue-500"> à terminer avant : <%= project.deadline.strftime("%d %m %Y")%> (encore <%= -project.day_until_end  %> jours)</p>
          </div>
      </div>
    </div>
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="container background">
  <h3>Créer ton nouveau projet :</h3>
  <%= render "form", projects: @project %>
</div>

app/views/projects/show.html.erb
<div class="project background container pt-2 pb-2 mt-1">
    <div class="background-img rounded"
         style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('<%= cl_image_path @project.photo.key, width: 1200, height: 500, crop: :fill %>')">
        <div class="p-2 d-flex justify-content-between text-white h-100">
            <h1 data-name="<%= @project.name %>" data-percent="<%= @project.project_advancement.round %>" class="project-title mb-2 w-50"><%= @project.name %></h1>
            <div class="d-flex flex-column justify-content-between">
              <p id="pourcentage"><%= @project.project_advancement.round %>% réalisé !</p>
              <p class="mb-2"> à terminer avant : <%= @project.deadline.strftime("%d %m %Y") %> (encore <%= -@project.day_until_end  %> jours)</p>
            </div>
        </div>
    </div>
    <div class="mt-4 d-flex justify-content-between">
      <button type="button" class="btn btn-gradient" data-toggle="modal" data-target="#editProject">
        Modifier le projet
      </button>
      <% if current_user.admin %>
        <%= link_to "Effacer",
        project_path(@project),
        method: :delete,
        data: { confirm: "Es-tu certain ?" },
        class: "mr-4 text-danger" %>
      <% end %>
    </div>


    <div id="igXPBar" style="opacity: 1; display: block;">
      <div id="igXPBarProg" style="background-color: rgb(251, 192, 45); width: <%= @project.project_advancement %>%;"></div>
    </div>


    <div class="p-2 mt-2 bg-white rounded">
      <p class="text-gray"><%= @project.rich_body  %></p>
      <div class="d-flex justify-content-between row">

        <div class="tasks-display tasks p-2 border col-md-4 col-lg-4 col-12 col-sm-6">
          <div class="card-tasks">
            <u><p>Liste des tâches :</p></u>
          <% @tasks.each do |task| %>
            <li class="my-2 d-flex justify-content-between">
            <p <% if task.completed == true %> class="checked"<% end %>><%= task.name.capitalize %></p>
            <div>
              <%= form_for [ @project, task] do |f| %>
              <div class="btn-box">
                <%= f.check_box :completed, onclick: "(this).closest('form').submit();"%>
              </div>
              <% end %>
            <% end %>
            </div>
            </li>
            <div class="text-center d-flex align-items-end justify-content-around">
              <button type="button" class="btn btn-gradient" data-toggle="modal" data-target="#addTask">
                Ajouter une tâche
              </button>
              <button type="button" class="btn btn-gradient" data-toggle="modal" data-target="#editTasks">
                Modifier les tâches
              </button>
            </div>
          </div>
          </div>

    <div class="tasks-display tasks p-2 border col-md-4 col-lg-3 col-12 col-sm-5">
      <div class="card-buys">
        <u><span>Liste des achats :</span></u>
        <% @buyings.each do |buying| %>
        <li class="my-2 d-flex">
          <span><%= buying.number %>&nbspx&nbsp</span>
          <span> <%= buying.name.capitalize %> </span>(<span> <%= buying.value.round(2) %>€ </span>)
          <span>&nbsp=&nbsp<%= (buying.number * buying.value).round(2)  %> €</span>
          <% end %>
        </li>
        <hr class="m-2 p-1">
        <div class="text-right m-2">
          <span class="m-2 h4">Total : <%= @project.value_project.round(2)  %> €</span>
        </div>
        </div>
        <div class="text-center d-flex align-items-end justify-content-center">
          <button type="button" class="btn btn-gradient" data-toggle="modal" data-target="#addBuying">
            Ajouter/modifier un achat
          </button>
          <!-- <button type="button" class="btn btn-gradient" data-toggle="modal" data-target="#editBuyings">
            Modifier les achats
          </button> -->
      </div>
    </div>

    <div class="tasks-display tasks p-2 border col-md-4 col-lg-4 col-12 col-sm-6">
      <u><span class="text-center"> Qui était la ? </span></u>
      <div class="card-whos">

        <% @usersprojects_past.each do |userproject| %>
        <li>
          <span><%= cl_image_tag userproject.user.photo.key, width: 150, crop: :thumb, gravity: :face, class: "avatar-small" %><strong><%= userproject.user.first_name.capitalize %></strong> <strong><%= userproject.user.last_name.split("").first.capitalize %>.</strong> du <%= userproject.date_start.strftime("%d %m %Y") %> au <%= userproject.date_end.strftime("%d %m %Y") %></span>
        </li>
          <% end %>
      <u><span class="text-center"> Qui sera la ? </span></u>
      <% @usersprojects_futur.each do |userproject| %>
      <li>
        <span><%= cl_image_tag userproject.user.photo.key, width: 150, crop: :thumb, gravity: :face, class: "avatar-small" %><strong>
        <%= userproject.user.first_name.capitalize %></strong> <strong><%= userproject.user.last_name.split("").first.capitalize %>.</strong>
        du <%= userproject.date_start.strftime("%d %m %Y") %> au <%= userproject.date_end.strftime("%d %m %Y") %>
        <% if userproject.user == current_user %>
          <%= link_to edit_project_usersproject_path(@project, userproject), class: 'edit-button' do %>
          <%= icon('fas', 'wrench')  %>
          <% end %>
          <%= link_to project_usersproject_path(@project, userproject), class: 'edit-button', method: :delete, data: { confirm: "Es-tu certain ?" } do %>
          <%= icon('fas', 'trash')  %>
          <% end %>
        <% end %>
       </span>
      </li>
        <% end %>
      </div>
      <div class="btn-bottom text-center d-flex align-items-end justify-content-center">
      <button type="button" class="btn btn-gradient bottom" data-toggle="modal" data-target="#joinProject">
        Rejoindre le projet
      </button>
    </div>
      </div>
    </div>
    <div class="comments mt-2">
        <% @comments.each do |comment| %>
        <div class="comment-msg">
        <div class="d-flex">
          <div>
            <%= cl_image_tag comment.user.photo.key, width: 150, crop: :thumb, gravity: :face, class: "avatar-small" %>
          </div >
          <span class="p-1">De <%= comment.user.first_name %> le :<%= comment.created_at.strftime("%d %m %Y") %></span>
        </div>
        <div class="p-1">
          <%= comment.rich_body %>
        </div>
      </div>
      <% end %>
      <div class="text-center">
          <button type="button" class="btn btn-gradient text-center" data-toggle="modal" data-target="#Question">
            Poser une question ?
          </button>
        </div>
    </div>
  </div>
</div>

<!-- modal projet-->
<div class="modal fade" id="editProject" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Vous pouvez modifier les données</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
            <%= render "form", projects: @project %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- modal achat-->
<div class="modal fade" id="addBuying" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Merci de noter le nom, la quantité et le prix unitaire. </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <%= simple_form_for [ @project, @buying ], :remote => true do |f| %>
          <div class="form-inputs">
            <%= f.input :name, placeholder: "Description(nom)" %>
            <%= f.input :number, placeholder: "Nb unité" %>
            <%= f.input :value, placeholder: "Prix unitaire" %>
          </div>
          <div class="mt-2 form-actions container text-center">
            <%= f.button :submit, "Ajouter un achat", class: "btn btn-gradient" %>
          </div>
          <% end %>
        </div>
        <div class="container mt-2">
          <% @buyings.each do |buying| %>
            <li>
              <span><%= buying.name.capitalize %></span>
              <span> <%= link_to "Modifier", edit_project_buying_path(@project, buying) %></span>
              <%= link_to "Effacer",
              project_buying_path(@project, buying),
              method: :delete,
              data: { confirm: "Es-tu certain ?" },
              class: "mr-4 text-danger" %>
            </li>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- modal taches-->
<div class="modal fade" id="addTask" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Merci d'inscrire le nom de la tâche</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <%= simple_form_for [ @project, @task ], :remote => true do |f| %>
          <div class="form-inputs">
            <%= f.input :name, placeholder: "Description de la tâche" %>
          </div>
          <div class="mt-2 form-actions container text-center modal-footer">
            <%= f.button :submit, class: "btn btn-gradient" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- modal rejoindre le projet-->
<div class="modal fade" id="joinProject" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Quand es-tu dispo ?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <%= simple_form_for [ @project, @usersproject ] do |f| %>
          <div class="form-inputs flatpickr">
            <span>Date de début</span>
            <%= f.text_field :date_start, data: { behavior: "flatpickr"} %>
            <span>Date de fin</span>
            <%= f.text_field :date_end, data: { behavior: "flatpickr"}  %>
          </div>
          <div class="mt-2 form-actions text-center modal-footer">
            <%= f.button :submit, "Rejoindre le projet ?", class: "btn btn-gradient" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- modal Questions-->
<div class="modal fade" id="Question" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class=" modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Quelle tâche veux-tu modifier ?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body d-flex justify-content-between">
        <div class="container">
          <%= simple_form_for [ @project, @comment ] do |f| %>
          <div class="form-inputs">
            <%= f.rich_text_area :rich_body, placeholder: 'Tu peux commencer à écrire ici...         Il est possible d\'insérer des images.' %>
          </div>
          <div class="mt-2 form-actions container text-center modal-footer">
            <%= f.button :submit, class: "btn btn-gradient" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- modal modifier les taches-->
<div class="modal fade" id="editTasks" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Quelle tâche veux-tu modifier ?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body d-flex flex-column justify-content-between">
        <% @tasks.each do |task| %>
        <div class="">
          <span><%= task.name.capitalize %></span>
          <span> <%= link_to "Modifier", edit_project_task_path(@project, task) %></span>
          <%= link_to "Effacer",
          project_task_path(@project, task),
          method: :delete,
          data: { confirm: "Es-tu certain ?" },
          class: "mr-4 text-danger"%>
          <% end %>
        </div>
      </div>
      </div>
    </div>
  </div>