config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  resources :blogs
  resources :famillies, only: [:new, :create, :edit, :destroy, :update ]
  resources :rooms do
    resources :reservations, only: [:new, :create, :edit, :destroy, :update, :index ]
    resources :perks, only: [:new, :create, :edit, :destroy, :update, :index ]
  end
  resources :tasks, only: [:show, :update]
  resources :buyings, only: [:show, :update]
  resources :projects do
    resources :tasks, only: [:new, :create, :edit, :destroy, :update]
    resources :buyings, only: [:new, :create, :edit, :destroy, :update ]
    resources :usersprojects, only: [:new, :create, :edit, :destroy, :update ]
    resources :comments, only: [:new, :create, :edit, :destroy, :update ]
  end
  namespace :my do
    resources :famillies, only: [ :index ]
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :house
  has_many :reservations
  validates :name, presence: true

  def unavailable_dates
    reservations.pluck(:date_in, :date_out).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:edit, :update, :show, :destroy]

  def index
    @rooms = policy_scope(Room.all)
  end

  def show
    @perks = Perk.where(room_id: @room)
    @reservation = Reservation.new
    @reservations = Reservation.where(room_id: @room)
    authorize @room
  end

  def new
  @room = Room.new
  authorize @room
  end

  def edit
    authorize @room
    @room = Room.find(params[:id])
  end

  def update
    authorize @room
    @room = Room.find(params[:id])
    if @room.update(room_params)
      redirect_to room_path(@room)
    else
      render :edit
    end
  end

  def create
    @room = Room.new(room_params)
    @room.house = House.find(1)
    authorize @room
    if @room.save!
      redirect_to room_path(@room)
    else
      render :show
    end
  end

  def destroy
    authorize @room
    @room.destroy
    redirect_to rooms_path
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:name)
  end
end

app/views/rooms/_form.html.erb
<%= simple_form_for [ @room, ], :remote => true do |f| %>
<div class="form-inputs flatpickr">
<%= f.input :name, input_html: { placeholder: " Chambre Arc-en-ciel" } %>
</div>
<div class="mt-2 form-actions text-center">
  <%= f.button :submit, "Valider la création ?", class: "btn btn-gradient" %>
</div>
<% end %>

app/views/rooms/edit.html.erb
<div class="container background p-2">
  <h3>Modifies une chambre :</h3>
  <%= render "form", rooms: @rooms %>
</div>

app/views/rooms/index.html.erb
<div class="container">
  <% @rooms.each do |room| %>
  <div class="shadow bg-black mt-1">
    <div class=" bg-size bg-cover bg-center">
      <div class="p-4 h-32 flex items-end text-black">
        <h3 class="mb-2 text-4xl"><%= room.house.name %></h3>
        <h3 class="mb-2 text-4xl"><%= room.name %></h3>
      </div>
    </div>
    <div class="mt-8 pl-2 d-flex align-items-end justify-content-between">
      <%= link_to room_path(room) do %>
      <p class="no-underline mr-4 text-blue-500 hover:text-blue-400"><strong>En savoir plus</strong></p>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/rooms/new.html.erb
<div class="container background p-2">
  <h3>Ajoutes une chambre :</h3>
  <%= render "form", rooms: @rooms %>
</div>

app/views/rooms/show.html.erb
<div class="room background container mt-1">
  <div class=" mt-1">
    <div class=" bg-size bg-cover bg-center d-flex justify-content-between">
      <div class="p-4 room-title">
        <h3 class="mb-2"><%= @room.house.name %></h3>
        <h3 class="mb-2"><%= @room.name %></h3>
      </div>
      <div class="room-elements">
        <% @perks.each do |perk| %>
          <li><span><%= perk.number %> - <%= perk.name  %>
            <%= link_to edit_room_perk_path(@room, perk), class: 'edit-button' do %>
            <%= icon('fas', 'wrench')  %>
            <% end %>
            <%= link_to room_perk_path(@room, perk), class: 'edit-button', method: :delete, data: { confirm: "Es-tu certain ?" } do %>
            <%= icon('fas', 'trash')  %>
            <% end %>
          </span></li>
        <% end %>
      </div>
    </div>

    <div class="room-reza">
      <% @reservations.each do |reservation|%>
      <li><%= cl_image_tag reservation.user.photo.key, width: 150, crop: :thumb, gravity: :face, class: "avatar-small" %>
        <% Familly.where(user_id: reservation.user.id).each do |member| %> <%= member.prenom  %>,   <% end %> <%= reservation.user.first_name %> du <%= reservation.date_in  %> au <%= reservation.date_out %>
        <% if reservation.user == current_user %>
          <%= link_to edit_room_reservation_path(@room, reservation), class: 'edit-button' do %>
          <%= icon('fas', 'wrench')  %>
          <% end %>
          <%= link_to room_reservation_path(@room, reservation), class: 'edit-button', method: :delete, data: { confirm: "Es-tu certain ?" } do %>
          <%= icon('fas', 'trash')  %>
          <% end %>
        <% end %>
      </li>
      <% end %>
    </div>
    <div class="mt-4 d-flex justify-content-between">
      <button type="button" class="btn btn-gradient" data-toggle="modal" data-target="#editRoom">
        Modifier la chambre
      </button>
      <%= link_to "Nouvelle reservation", new_room_reservation_path(@room, @reservation), class: "btn btn-gradient" %>
      <%= link_to "Ajouter un élément à la chambre", new_room_perk_path(@room, @perk), class: "btn btn-gradient" %>
    </div>
  </div>
</div>

<!-- modal room-->
<div class="modal fade" id="editRoom" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Vous pouvez modifier les données</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <%= render "form", rooms: @room %>
        </div>
      </div>
    </div>
  </div>
</div>